### ISSUE TITLE
getActiveModifications is returning TextualMod -> rename?

### ISSUE THREAD

**Issue by reckseba** [digitalservicebund/ris-norms#353]
https://github.com/digitalservicebund/ris-norms/blob/92c6cac62b8da19677c77a0bdb5bed52f17b4cb8/backend/src/main/java/de/bund/digitalservice/ris/norms/domain/entity/Norm.java#L189

While implementing I got confused by the name as this method returns a TextualMod instead of a real ActiveMod now. 

Shall we rename it to getTextualModifications and implement a real getActiveModifications that does what it says?

**Comment by VictorDelCampo** [comment]
It can be confusing yes but actually there can always only be max 1 `akn:activeModifications` (plural). And this node contains a list of `akn:textualMod` which are the actual text modifications (there can also be a list of `akn:forceMod` together but let's not complicate the explanation now). So yes we wanted to stay as close as possible to LDML.de BUT how would we then call the method for getting the passiv mods? The node `akn:passiveModifications` (plural) and also contains lists of  `akn:textualMod` and  `akn:forceMod`.

Actually the more proper way for the naming one mod would have been `akn:activeModification` (singular) and `akn:passiveModification` (plural) and probably then use an attribute for specifying if textual-mod or force-mod.

We will probably need to change the naming of the method when we need to also retrieve the list of `akn:forceMod` but for the time being I think keeping those names are they are is fine.

@malte-laukoetter what do you think?

**EDIT**: Malte now I see the changes you made, removing the classes ActiveModification and PassiveModification and just havig the TextualMod and accessing the specific parts (like for the active-mod getting the destinationEli and destinationEid) where we need them. But this means, compared to the approach before with different classes, that you could now call a method of Href and get an optional.empty that you then need to handle in your code, rather than not permitting at all using a specific get-method... but on the contrary there is only 1 `akn:textualMod `element in LDML.de and we wanted to stay as close as possible... I think I am convincing myself while writing...

**Comment by malte-laukoetter** [comment]
The naming of `getActiveModifications` is also something i stumbled over a couple of times, so a different name for it would be nice, but I don't think it is possible to do that with a simple renaming.

A simple `getTextualMods()` would not work as they can exist in both `akn:activeModificiations` and `akn:passiveModifications` and have a different meaning depending on which element they reside in (and one norm can have both). Maybe something like `getActiveModifications().getTextualMods()` would work? So creating new Domain Objects for both activeModifications and passiveModifications?

**Comment by VictorDelCampo** [comment]
I would also go for new domain objects and for now they would only have `.getTextualMods()` but later they will also probably get the `.getForceMods()`

**Comment by VictorDelCampo** [comment]
This can be closed @reckseba ?
